// String sets for the invoice template. This file is *concatenated* in front of
// `invoice.typ` by `saas_invoice::pdf` — there is no file system behind the Typst
// `World`, so neither file may `#import` the other.

#let strings = (
	hu: (
		"title.NORMAL": "SZÁMLA",
		"title.STORNO": "SZTORNÓ SZÁMLA",
		"seller": "Szállító",
		"buyer": "Vevő",
		"number": "Számla sorszáma",
		"issued": "Számla kelte",
		"fulfilment": "Teljesítés",
		"due": "Fizetési határidő",
		"payment": "Fizetési mód",
		"currency": "Pénznem",
		"original": "Sztornózott számla",
		"tax-number": "Adószám",
		"eu-vat-id": "Közösségi adószám",
		"group-tax-no": "Csoportazonosító",
		"bank": "Bankszámlaszám",
		"col.no": "#",
		"col.description": "Megnevezés",
		"col.qty": "Mennyiség",
		"col.unit": "Egység",
		"col.unit-price": "Egységár",
		"col.discount": "Kedvezmény",
		"col.net": "Nettó",
		"col.vat-rate": "Áfa",
		"col.vat": "Áfa összeg",
		"col.gross": "Bruttó",
		"vat-summary": "Áfa összesítő",
		"total": "Összesen",
		"payable": "Fizetendő (kerekítve)",
		"rate": "Árfolyam",
		"rate.date": "Árfolyam napja",
		"rate.source": "Árfolyam forrása",
		"huf-equivalent": "Forint egyenérték",
		"notes": "Megjegyzés",
		"payment.TRANSFER": "Átutalás",
		"payment.CARD": "Bankkártya",
		"payment.CASH": "Készpénz",
		"payment.OTHER": "Egyéb",
		"vat.eufad37": "Az áfa fizetésére a vevő kötelezett — fordított adózás (Áfa tv. 37. §).",
		"vat.ho": "Területi hatályon kívüli — az ügylet nem tartozik a magyar áfa hatálya alá.",
		"vat.aam": "Alanyi adómentes — a számla áfát nem tartalmaz (Áfa tv. 187–196. §).",
		"vat.tam": "Tárgyi adómentes ügylet (Áfa tv. 85–86. §).",
		"vat.atk": "Az áfa tárgyi hatályán kívüli ügylet.",
	),
	en: (
		"title.NORMAL": "INVOICE",
		"title.STORNO": "CREDIT NOTE",
		"seller": "Seller",
		"buyer": "Buyer",
		"number": "Invoice number",
		"issued": "Issue date",
		"fulfilment": "Fulfilment date",
		"due": "Due date",
		"payment": "Payment method",
		"currency": "Currency",
		"original": "Cancelled invoice",
		"tax-number": "Tax number",
		"eu-vat-id": "EU VAT ID",
		"group-tax-no": "VAT group ID",
		"bank": "Bank account",
		"col.no": "#",
		"col.description": "Description",
		"col.qty": "Qty",
		"col.unit": "Unit",
		"col.unit-price": "Unit price",
		"col.discount": "Discount",
		"col.net": "Net",
		"col.vat-rate": "VAT",
		"col.vat": "VAT amount",
		"col.gross": "Gross",
		"vat-summary": "VAT summary",
		"total": "Total",
		"payable": "Payable (rounded)",
		"rate": "Exchange rate",
		"rate.date": "Rate date",
		"rate.source": "Rate source",
		"huf-equivalent": "HUF equivalent",
		"notes": "Notes",
		"payment.TRANSFER": "Bank transfer",
		"payment.CARD": "Card",
		"payment.CASH": "Cash",
		"payment.OTHER": "Other",
		"vat.eufad37": "Reverse charge — VAT is payable by the customer (Art. 196 of Directive 2006/112/EC).",
		"vat.ho": "Outside the territorial scope of Hungarian VAT.",
		"vat.aam": "VAT exempt under the Hungarian subjective exemption scheme (Áfa tv. 187–196. §); no VAT is charged.",
		"vat.tam": "Exempt supply under Áfa tv. 85–86. §; no VAT is charged.",
		"vat.atk": "Outside the material scope of VAT.",
	),
)

// Missing key renders as the key itself: a gap is visible on the page, never a crash.
#let t(lang, key) = {
	// Not `set`: that is a Typst keyword, and binding it failed the *whole* template with
	// "expected pattern, found keyword `set`" — every PDF, not just a missing string.
	let bundle = strings.at(lang, default: strings.en)
	bundle.at(key, default: key)
}
