//! The extensibility claim, executed: a consumer application declares its own store trait,
//! implements it for `PgStore` (legal under the orphan rule — the trait is local here), ships its
//! own migration [`Module`] beside the framework's, registers the store as an extension and reads
//! it back out of `app.extensions`. Everything below uses only the public surface a real consumer
//! has. Skips when `PG_TEST_URL` is unset.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod common;

use std::sync::Arc;

use async_trait::async_trait;
use saas_core::AppBuilder;
use saas_core::config::Config;
use saas_core::error::ClResult;
use saas_core::store::CoreStore;
use sqlx::PgConnection;
use store_adapter_postgres::util::DbExt;
use store_adapter_postgres::{FRAMEWORK, Fut, Module, PgStore, schema};

const M_TICKETS: Module = Module { name: "consumer", version: 1, apply: tickets };

fn tickets(conn: &mut PgConnection, _from: i64) -> Fut<'_> {
	Box::pin(async move {
		sqlx::raw_sql(
			"CREATE TABLE tickets (
				id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				title  TEXT NOT NULL,
				status TEXT NOT NULL DEFAULT 'OPEN'
			);",
		)
		.execute(conn)
		.await
		.db()?;
		Ok(())
	})
}

#[async_trait]
trait TicketStore: Send + Sync + 'static {
	async fn create_ticket(&self, title: &str) -> ClResult<i64>;
	async fn ticket(&self, id: i64) -> ClResult<Option<(String, String)>>;
}

#[async_trait]
impl TicketStore for PgStore {
	/// Insert and read back in one write transaction — the consumer's table is in the
	/// framework's database and under the framework's write lock.
	async fn create_ticket(&self, title: &str) -> ClResult<i64> {
		let tx = self.write_tx().await?;
		let id: i64 = sqlx::query_scalar("INSERT INTO tickets (title) VALUES ($1) RETURNING id")
			.bind(title)
			.fetch_one(&mut *tx.lock().await?)
			.await
			.db()?;
		tx.commit().await?;
		Ok(id)
	}

	async fn ticket(&self, id: i64) -> ClResult<Option<(String, String)>> {
		sqlx::query_as("SELECT title, status FROM tickets WHERE id = $1")
			.bind(id)
			.fetch_optional(self.read_pool())
			.await
			.db()
	}
}

#[tokio::test]
async fn consumer_extends_the_store() {
	let Some(db) = common::TestDb::new().await else { return };
	let store = db.open().await;

	store.migrate(&[FRAMEWORK, M_TICKETS]).await.unwrap();

	let applied: Vec<(String, i64)> =
		sqlx::query_as("SELECT module, version FROM schema_version ORDER BY module")
			.fetch_all(store.read_pool())
			.await
			.unwrap();
	assert_eq!(applied, [("consumer".into(), 1), (schema::MODULE_NAME.into(), schema::VERSION)]);

	let dir = std::env::temp_dir();
	let config = Config {
		master_key: [7; 32],
		db_path: String::new(),
		data_dir: dir.to_string_lossy().into_owned(),
		listen: String::new(),
		base_url: String::new(),
		jobs_workers: None,
	};
	let tickets: Arc<dyn TicketStore> = Arc::new(store.clone());
	let app = AppBuilder::new()
		.config(config)
		.store(Arc::new(store.clone()) as Arc<dyn CoreStore>)
		.extension(tickets)
		.build()
		.await
		.unwrap();

	let tickets = app.extensions.get::<Arc<dyn TicketStore>>().expect("TicketStore extension");

	let id = tickets.create_ticket("printer on fire").await.unwrap();
	let got = tickets.ticket(id).await.unwrap().expect("ticket round-trips");
	assert_eq!(got, ("printer on fire".to_string(), "OPEN".to_string()));
	assert!(tickets.ticket(id + 1).await.unwrap().is_none());
}

// vim: ts=4
