// SPDX-License-Identifier: MPL-2.0
//! The PostgreSQL app DB under `mintworks_store_conformance`'s app-DB suites.
//!
//! Needs `PG_TEST_URL` (a `postgres://…/<db>` URL whose role has `CREATEDB` and `CREATEROLE`);
//! unset, every test prints a skip line and passes. Each test creates its own database and drops
//! it afterwards.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod common;

use mintworks_appdb_postgres::{Fut, Module, PgAppDb};
use mintworks_core::ClResult;
use mintworks_script::AppDb;
use mintworks_store_conformance::{AppDbHarness, TestModule};
use sqlx::PgConnection;

/// The suite's handle on a scratch database; dropping it drops the database.
struct PgHarness {
	tmp: common::TestDb,
	db: PgAppDb,
}

impl AppDbHarness for PgHarness {
	type Db = PgAppDb;

	async fn fresh(_name: &str) -> Option<Self> {
		let tmp = common::TestDb::new().await?;
		Some(Self { db: tmp.open(), tmp })
	}

	fn db(&self) -> &PgAppDb {
		&self.db
	}

	fn open(&self) -> PgAppDb {
		self.tmp.open()
	}

	/// `?` → `$1`, `$2`, …; the suite's SQL holds no `?` operator and no `?` inside a literal.
	fn sql(sql: &str) -> String {
		let mut n = 0;
		let mut out = String::with_capacity(sql.len() + 8);
		for c in sql.chars() {
			if c == '?' {
				n += 1;
				out.push('$');
				out.push_str(&n.to_string());
			} else {
				out.push(c);
			}
		}
		out
	}

	async fn migrate(db: &PgAppDb, modules: &[TestModule]) -> ClResult<()> {
		let modules: Vec<Module> = modules
			.iter()
			.map(|m| match *m {
				TestModule::Notes { version } => {
					Module { name: "notes", version, apply: create_notes }
				}
				TestModule::Seed => Module { name: "seed", version: 1, apply: seed_notes },
				#[cfg(feature = "ai")]
				TestModule::Memory => mintworks_appdb_postgres::MEMORY,
				#[cfg(feature = "ai")]
				TestModule::Agent => mintworks_appdb_postgres::AGENT,
				// Unified features can turn `mintworks-store-conformance/ai` on without this crate's `ai`.
				#[cfg(not(feature = "ai"))]
				#[allow(unreachable_patterns)]
				_ => unreachable!("an ai module needs --features ai"),
			})
			.collect();
		db.migrate(&modules).await
	}

	async fn index_names(db: &PgAppDb) -> Vec<String> {
		let sql = "SELECT indexname::text AS name FROM pg_indexes
			  WHERE schemaname = current_schema() AND indexname LIKE 'ix:%'";
		let rows = db.query(sql, &[], 10_000).await.unwrap();
		let mut names: Vec<String> =
			rows.iter().map(|r| r["name"].as_str().unwrap().to_owned()).collect();
		// Byte order in Rust: the database's collation may ignore the `:`/`_` punctuation.
		names.sort();
		names
	}
}

fn create_notes(conn: &mut PgConnection, _from: i64) -> Fut<'_> {
	Box::pin(async move {
		let sql = "CREATE TABLE notes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, body TEXT)";
		sqlx::query(sql).execute(conn).await.unwrap();
		Ok(())
	})
}

fn seed_notes(conn: &mut PgConnection, _from: i64) -> Fut<'_> {
	Box::pin(async move {
		sqlx::query("INSERT INTO notes (body) VALUES ('seed')")
			.execute(conn)
			.await
			.unwrap();
		Ok(())
	})
}

mintworks_store_conformance::appdb_tests!(PgHarness);

#[cfg(feature = "ai")]
mod memory {
	mintworks_store_conformance::memory_tests!(super::PgHarness);
}

#[cfg(feature = "ai")]
mod thread {
	mintworks_store_conformance::thread_tests!(super::PgHarness);
}

// vim: ts=4
