//! `saas-agent`'s thread store: the app-DB module `agent` and `impl ThreadStore for PgAppDb`.

use async_trait::async_trait;
use saas_agent::store::{Message, NewMessage, Thread, ThreadStore};
use saas_core::{
	ClResult,
	prelude::{ThreadId, Timestamp},
};
use sqlx::PgConnection;

use crate::{Fut, Module, PgAppDb, util::DbExt};

/// The `agent` app-DB module. Three-edit rule: change `SCHEMA`, add an `if from < N` step to
/// `apply`, bump `VERSION`. Version 1 on PostgreSQL: the SQLite chain's history never shipped here.
pub const AGENT: Module = Module { name: "agent", version: VERSION, apply };

const VERSION: i64 = 1;

const SCHEMA: &[&str] = &[
	"CREATE TABLE agent_threads (
		id				BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		uid				TEXT NOT NULL UNIQUE,
		org				TEXT NOT NULL,
		subject			TEXT,
		title			TEXT,
		summary			TEXT,
		token_estimate	BIGINT NOT NULL DEFAULT 0,
		last_model		TEXT,
		created_at		BIGINT NOT NULL,
		updated_at		BIGINT NOT NULL
	)",
	"CREATE INDEX idx_agent_threads_org ON agent_threads (org)",
	"CREATE TABLE agent_messages (
		id				BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		thread_id		BIGINT NOT NULL REFERENCES agent_threads(id),
		role			TEXT NOT NULL,
		content			TEXT NOT NULL,
		tool_calls		TEXT,
		tool_call_id	TEXT,
		compacted		BOOLEAN NOT NULL DEFAULT false,
		created_at		BIGINT NOT NULL
	)",
	"CREATE INDEX idx_agent_messages_thread ON agent_messages (thread_id, id)",
];

fn apply(conn: &mut PgConnection, from: i64) -> Fut<'_> {
	Box::pin(async move {
		if from == 0 {
			for &sql in SCHEMA {
				sqlx::query(sql).execute(&mut *conn).await.db()?;
			}
		}
		Ok(())
	})
}

const THREAD_COLS: &str =
	"id, uid, org, subject, title, summary, token_estimate, last_model, created_at, updated_at";

type ThreadRow = (
	i64,
	String,
	String,
	Option<String>,
	Option<String>,
	Option<String>,
	i64,
	Option<String>,
	i64,
	i64,
);

fn thread(r: ThreadRow) -> Thread {
	Thread {
		id: r.0,
		uid: ThreadId::from_trusted(r.1),
		org: r.2,
		subject: r.3,
		title: r.4,
		summary: r.5,
		token_estimate: r.6,
		last_model: r.7,
		created_at: Timestamp(r.8),
		updated_at: Timestamp(r.9),
	}
}

const MESSAGE_COLS: &str =
	"id, thread_id, role, content, tool_calls, tool_call_id, compacted, created_at";

type MessageRow = (i64, i64, String, String, Option<String>, Option<String>, bool, i64);

fn message(r: MessageRow) -> Message {
	Message {
		id: r.0,
		thread_id: r.1,
		role: r.2,
		content: r.3,
		tool_calls: r.4,
		tool_call_id: r.5,
		compacted: r.6,
		created_at: Timestamp(r.7),
	}
}

async fn append(
	c: &mut PgConnection,
	thread_id: i64,
	msgs: &[NewMessage<'_>],
	last_model: Option<&str>,
	token_estimate: i64,
) -> ClResult<()> {
	let now = Timestamp::now().0;
	for m in msgs {
		sqlx::query(
			"INSERT INTO agent_messages (thread_id, role, content, tool_calls, tool_call_id, \
			 created_at) VALUES ($1, $2, $3, $4, $5, $6)",
		)
		.bind(thread_id)
		.bind(m.role)
		.bind(m.content)
		.bind(m.tool_calls)
		.bind(m.tool_call_id)
		.bind(now)
		.execute(&mut *c)
		.await
		.db()?;
	}
	sqlx::query(
		"UPDATE agent_threads SET token_estimate = $1, last_model = COALESCE($2, last_model), \
		 updated_at = $3 WHERE id = $4",
	)
	.bind(token_estimate)
	.bind(last_model)
	.bind(now)
	.bind(thread_id)
	.execute(&mut *c)
	.await
	.db()?;
	Ok(())
}

async fn compact(
	c: &mut PgConnection,
	thread_id: i64,
	summary: &str,
	through_id: i64,
	token_estimate: i64,
) -> ClResult<()> {
	sqlx::query("UPDATE agent_messages SET compacted = true WHERE thread_id = $1 AND id <= $2")
		.bind(thread_id)
		.bind(through_id)
		.execute(&mut *c)
		.await
		.db()?;
	sqlx::query(
		"UPDATE agent_threads SET summary = $1, token_estimate = $2, updated_at = $3 WHERE id = $4",
	)
	.bind(summary)
	.bind(token_estimate)
	.bind(Timestamp::now().0)
	.bind(thread_id)
	.execute(&mut *c)
	.await
	.db()?;
	Ok(())
}

async fn erase_org(c: &mut PgConnection, org: &str) -> ClResult<u64> {
	sqlx::query(
		"DELETE FROM agent_messages WHERE thread_id IN (SELECT id FROM agent_threads WHERE org = $1)",
	)
	.bind(org)
	.execute(&mut *c)
	.await
	.db()?;
	let done = sqlx::query("DELETE FROM agent_threads WHERE org = $1")
		.bind(org)
		.execute(&mut *c)
		.await
		.db()?;
	Ok(done.rows_affected())
}

#[async_trait]
impl ThreadStore for PgAppDb {
	async fn thread_create(
		&self,
		org: &str,
		subject: Option<&str>,
		title: Option<&str>,
	) -> ClResult<Thread> {
		let now = Timestamp::now().0;
		let mut conn = self.conn(true).await?;
		let sql = format!(
			"INSERT INTO agent_threads (uid, org, subject, title, created_at, updated_at) \
			 VALUES ($1, $2, $3, $4, $5, $6) RETURNING {THREAD_COLS}"
		);
		let row = sqlx::query_as(sqlx::AssertSqlSafe(sql))
			.bind(ThreadId::generate().as_str())
			.bind(org)
			.bind(subject)
			.bind(title)
			.bind(now)
			.bind(now)
			.fetch_one(conn.get())
			.await
			.db()?;
		Ok(thread(row))
	}

	async fn thread_get(&self, uid: &ThreadId) -> ClResult<Option<Thread>> {
		let mut conn = self.conn(false).await?;
		let sql = format!("SELECT {THREAD_COLS} FROM agent_threads WHERE uid = $1");
		let row = sqlx::query_as(sqlx::AssertSqlSafe(sql))
			.bind(uid.as_str())
			.fetch_optional(conn.get())
			.await
			.db()?;
		Ok(row.map(thread))
	}

	async fn threads_list(&self, org: &str) -> ClResult<Vec<Thread>> {
		let mut conn = self.conn(false).await?;
		let sql = format!("SELECT {THREAD_COLS} FROM agent_threads WHERE org = $1 ORDER BY id");
		let rows = sqlx::query_as(sqlx::AssertSqlSafe(sql))
			.bind(org)
			.fetch_all(conn.get())
			.await
			.db()?;
		Ok(rows.into_iter().map(thread).collect())
	}

	async fn messages_append(
		&self,
		thread_id: i64,
		msgs: &[NewMessage<'_>],
		last_model: Option<&str>,
		token_estimate: i64,
	) -> ClResult<()> {
		write_tx!(self, "agent", |c| append(c, thread_id, msgs, last_model, token_estimate).await)
	}

	async fn messages_live(&self, thread_id: i64) -> ClResult<Vec<Message>> {
		let mut conn = self.conn(false).await?;
		let sql = format!(
			"SELECT {MESSAGE_COLS} FROM agent_messages WHERE thread_id = $1 AND NOT compacted \
			 ORDER BY id"
		);
		let rows = sqlx::query_as(sqlx::AssertSqlSafe(sql))
			.bind(thread_id)
			.fetch_all(conn.get())
			.await
			.db()?;
		Ok(rows.into_iter().map(message).collect())
	}

	async fn messages_all(&self, thread_id: i64) -> ClResult<Vec<Message>> {
		let mut conn = self.conn(false).await?;
		let sql =
			format!("SELECT {MESSAGE_COLS} FROM agent_messages WHERE thread_id = $1 ORDER BY id");
		let rows = sqlx::query_as(sqlx::AssertSqlSafe(sql))
			.bind(thread_id)
			.fetch_all(conn.get())
			.await
			.db()?;
		Ok(rows.into_iter().map(message).collect())
	}

	async fn compact(
		&self,
		thread_id: i64,
		summary: &str,
		through_id: i64,
		token_estimate: i64,
	) -> ClResult<()> {
		write_tx!(self, "agent", |c| compact(c, thread_id, summary, through_id, token_estimate)
			.await)
	}

	async fn org_erase(&self, org: &str) -> ClResult<u64> {
		write_tx!(self, "agent", |c| erase_org(c, org).await)
	}
}

// vim: ts=4
