//! `saas-memory`'s store: the app-DB module `memory` and `impl MemoryStore for PgAppDb`.
//!
//! No triggers (arch-9): `memory_docs.tsv` is rewritten by [`write_version`] in the same
//! transaction as the version insert, over the doc's path and current body.

use async_trait::async_trait;
use saas_core::{ClResult, prelude::Timestamp};
use saas_memory::{Doc, MemoryStore, NewVersion, SearchHit, Space, Version, WriteMode};
use sqlx::PgConnection;

use crate::{Fut, Module, PgAppDb, util::DbExt};

/// The `memory` app-DB module. Three-edit rule: change `SCHEMA`, add an `if from < N` step to
/// `apply`, bump `VERSION`.
pub const MEMORY: Module = Module { name: "memory", version: VERSION, apply };

const VERSION: i64 = 1;

/// `'simple'`, not a language configuration: content is multi-language, so no stemming.
const SCHEMA: &[&str] = &[
	"CREATE TABLE memory_spaces (
		id			BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		org			TEXT NOT NULL,
		key			TEXT NOT NULL,
		created_at	BIGINT NOT NULL,
		UNIQUE (org, key)
	)",
	"CREATE TABLE memory_docs (
		id			BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		space_id	BIGINT NOT NULL REFERENCES memory_spaces(id),
		path		TEXT NOT NULL,
		version		BIGINT NOT NULL,
		updated_at	BIGINT NOT NULL,
		tsv			TSVECTOR NOT NULL DEFAULT ''::tsvector,
		UNIQUE (space_id, path)
	)",
	"CREATE INDEX idx_memory_docs_tsv ON memory_docs USING GIN (tsv)",
	"CREATE TABLE memory_versions (
		id			BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		doc_id		BIGINT NOT NULL REFERENCES memory_docs(id),
		version		BIGINT NOT NULL,
		body		TEXT NOT NULL,
		author		TEXT NOT NULL,
		created_at	BIGINT NOT NULL,
		pdf_sha256	TEXT,
		UNIQUE (doc_id, version)
	)",
];

fn apply(conn: &mut PgConnection, from: i64) -> Fut<'_> {
	Box::pin(async move {
		if from == 0 {
			for &sql in SCHEMA {
				sqlx::query(sql).execute(&mut *conn).await.db()?;
			}
		}
		Ok(())
	})
}

/// `doc_id, version, body, author, created_at, pdf_sha256`.
type VersionRow = (i64, i64, String, String, i64, Option<String>);

fn version(r: VersionRow) -> Version {
	Version {
		doc_id: r.0,
		version: r.1,
		body: r.2,
		author: r.3,
		created_at: Timestamp(r.4),
		pdf_sha256: r.5,
	}
}

fn space(r: (i64, String, String, i64)) -> Space {
	Space { id: r.0, org: r.1, key: r.2, created_at: Timestamp(r.3) }
}

fn doc(r: (i64, i64, String, i64, i64)) -> Doc {
	Doc { id: r.0, space_id: r.1, path: r.2, version: r.3, updated_at: Timestamp(r.4) }
}

async fn write_version(c: &mut PgConnection, new: &NewVersion<'_>) -> ClResult<Version> {
	let now = Timestamp::now().0;
	sqlx::query(
		"INSERT INTO memory_spaces (org, key, created_at) VALUES ($1, $2, $3) \
		 ON CONFLICT (org, key) DO NOTHING",
	)
	.bind(new.org)
	.bind(new.space_key)
	.bind(now)
	.execute(&mut *c)
	.await
	.db()?;
	let space_id: i64 =
		sqlx::query_scalar("SELECT id FROM memory_spaces WHERE org = $1 AND key = $2")
			.bind(new.org)
			.bind(new.space_key)
			.fetch_one(&mut *c)
			.await
			.db()?;

	// Version 0 is a doc with no version yet; it lives only until the UPDATE below. `FOR UPDATE`
	// serializes concurrent writers of one doc, which SQLite's single writer did implicitly.
	sqlx::query(
		"INSERT INTO memory_docs (space_id, path, version, updated_at) VALUES ($1, $2, 0, $3) \
		 ON CONFLICT (space_id, path) DO NOTHING",
	)
	.bind(space_id)
	.bind(new.path)
	.bind(now)
	.execute(&mut *c)
	.await
	.db()?;
	let (doc_id, prev): (i64, i64) = sqlx::query_as(
		"SELECT id, version FROM memory_docs WHERE space_id = $1 AND path = $2 FOR UPDATE",
	)
	.bind(space_id)
	.bind(new.path)
	.fetch_one(&mut *c)
	.await
	.db()?;

	let body = match new.mode {
		WriteMode::Append if prev > 0 => {
			let old: String = sqlx::query_scalar(
				"SELECT body FROM memory_versions WHERE doc_id = $1 AND version = $2",
			)
			.bind(doc_id)
			.bind(prev)
			.fetch_one(&mut *c)
			.await
			.db()?;
			old + new.body
		}
		_ => new.body.to_owned(),
	};
	let version = prev + 1;
	sqlx::query(
		"INSERT INTO memory_versions (doc_id, version, body, author, created_at, pdf_sha256) \
		 VALUES ($1, $2, $3, $4, $5, $6)",
	)
	.bind(doc_id)
	.bind(version)
	.bind(&body)
	.bind(new.author)
	.bind(now)
	.bind(new.pdf_sha256)
	.execute(&mut *c)
	.await
	.db()?;
	sqlx::query(
		"UPDATE memory_docs SET version = $1, updated_at = $2, \
		 tsv = to_tsvector('simple', $3) || to_tsvector('simple', $4) WHERE id = $5",
	)
	.bind(version)
	.bind(now)
	.bind(new.path)
	.bind(&body)
	.bind(doc_id)
	.execute(&mut *c)
	.await
	.db()?;

	Ok(Version {
		doc_id,
		version,
		body,
		author: new.author.to_owned(),
		created_at: Timestamp(now),
		pdf_sha256: new.pdf_sha256.map(str::to_owned),
	})
}

/// Children before parents.
async fn erase_org(c: &mut PgConnection, org: &str) -> ClResult<u64> {
	for sql in [
		"DELETE FROM memory_versions WHERE doc_id IN (SELECT d.id FROM memory_docs d \
		 JOIN memory_spaces s ON s.id = d.space_id WHERE s.org = $1)",
		"DELETE FROM memory_docs WHERE space_id IN (SELECT id FROM memory_spaces WHERE org = $1)",
	] {
		sqlx::query(sql).bind(org).execute(&mut *c).await.db()?;
	}
	let done = sqlx::query("DELETE FROM memory_spaces WHERE org = $1")
		.bind(org)
		.execute(&mut *c)
		.await
		.db()?;
	Ok(done.rows_affected())
}

#[async_trait]
impl MemoryStore for PgAppDb {
	async fn spaces_list(&self, org: &str) -> ClResult<Vec<Space>> {
		let mut conn = self.conn(false).await?;
		let rows = sqlx::query_as(
			"SELECT id, org, key, created_at FROM memory_spaces WHERE org = $1 ORDER BY key",
		)
		.bind(org)
		.fetch_all(conn.get())
		.await
		.db()?;
		Ok(rows.into_iter().map(space).collect())
	}

	async fn space_get(&self, org: &str, key: &str) -> ClResult<Option<Space>> {
		let mut conn = self.conn(false).await?;
		let row = sqlx::query_as(
			"SELECT id, org, key, created_at FROM memory_spaces WHERE org = $1 AND key = $2",
		)
		.bind(org)
		.bind(key)
		.fetch_optional(conn.get())
		.await
		.db()?;
		Ok(row.map(space))
	}

	async fn docs_list(&self, space_id: i64) -> ClResult<Vec<Doc>> {
		let mut conn = self.conn(false).await?;
		let rows = sqlx::query_as(
			"SELECT id, space_id, path, version, updated_at FROM memory_docs \
			 WHERE space_id = $1 ORDER BY path",
		)
		.bind(space_id)
		.fetch_all(conn.get())
		.await
		.db()?;
		Ok(rows.into_iter().map(doc).collect())
	}

	async fn doc_get(&self, space_id: i64, path: &str) -> ClResult<Option<Doc>> {
		let mut conn = self.conn(false).await?;
		let row = sqlx::query_as(
			"SELECT id, space_id, path, version, updated_at FROM memory_docs \
			 WHERE space_id = $1 AND path = $2",
		)
		.bind(space_id)
		.bind(path)
		.fetch_optional(conn.get())
		.await
		.db()?;
		Ok(row.map(doc))
	}

	async fn version_get(&self, doc_id: i64, version: Option<i64>) -> ClResult<Option<Version>> {
		let mut conn = self.conn(false).await?;
		let row: Option<VersionRow> = sqlx::query_as(
			"SELECT doc_id, version, body, author, created_at, pdf_sha256 FROM memory_versions \
			 WHERE doc_id = $1 \
			 AND version = coalesce($2::bigint, (SELECT version FROM memory_docs WHERE id = $1))",
		)
		.bind(doc_id)
		.bind(version)
		.fetch_optional(conn.get())
		.await
		.db()?;
		Ok(row.map(self::version))
	}

	async fn versions_list(&self, doc_id: i64) -> ClResult<Vec<Version>> {
		let mut conn = self.conn(false).await?;
		let rows: Vec<VersionRow> = sqlx::query_as(
			"SELECT doc_id, version, body, author, created_at, pdf_sha256 FROM memory_versions \
			 WHERE doc_id = $1 ORDER BY version",
		)
		.bind(doc_id)
		.fetch_all(conn.get())
		.await
		.db()?;
		Ok(rows.into_iter().map(version).collect())
	}

	async fn version_write(&self, new: &NewVersion<'_>) -> ClResult<Version> {
		write_tx!(self, "memory", |c| write_version(c, new).await)
	}

	/// `plainto_tsquery`: the user's words, ANDed, never PostgreSQL's tsquery syntax.
	async fn search(
		&self,
		org: &str,
		space_id: Option<i64>,
		query: &str,
		limit: u32,
	) -> ClResult<Vec<SearchHit>> {
		if query.trim().is_empty() {
			return Ok(Vec::new());
		}
		let mut conn = self.conn(false).await?;
		let rows: Vec<(String, String, i64, String)> = sqlx::query_as(
			"SELECT s.key, d.path, d.version, ts_headline('simple', v.body, q, \
			 'StartSel=**, StopSel=**, MaxWords=16, MinWords=4, MaxFragments=1') \
			 FROM plainto_tsquery('simple', $1) q \
			 JOIN memory_docs d ON d.tsv @@ q \
			 JOIN memory_spaces s ON s.id = d.space_id \
			 JOIN memory_versions v ON v.doc_id = d.id AND v.version = d.version \
			 WHERE s.org = $2 AND ($3::bigint IS NULL OR s.id = $3) \
			 ORDER BY ts_rank(d.tsv, q) DESC, d.id LIMIT $4",
		)
		.bind(query)
		.bind(org)
		.bind(space_id)
		.bind(i64::from(limit))
		.fetch_all(conn.get())
		.await
		.db()?;
		Ok(rows
			.into_iter()
			.map(|(space_key, path, version, snippet)| SearchHit {
				space_key,
				path,
				version,
				snippet,
			})
			.collect())
	}

	async fn org_erase(&self, org: &str) -> ClResult<u64> {
		write_tx!(self, "memory", |c| erase_org(c, org).await)
	}
}

// vim: ts=4
