//! The framework's current schema in PostgreSQL, as one `CREATE` pass for a fresh database —
//! the counterpart of `store-adapter-sqlite/src/schema.rs`, with its own version chain.
//!
//! Translation rules (`claude-docs/postgres-adapters-design.md`): `id` is
//! `BIGINT GENERATED BY DEFAULT AS IDENTITY`, timestamps and SQLite's 0/1 booleans stay `BIGINT`,
//! blobs are `BYTEA`, and a `COLLATE NOCASE` unique is a unique index on `lower(col)`, so a lookup
//! on such a column compares `lower()` too. No trigger appears anywhere (arch-9).

use sqlx::PgConnection;

use saas_core::error::{ClResult, Error};
use saas_core::prelude::{OrgId, Timestamp};

use crate::migrate::{Fut, Module};
use crate::util::DbExt;

/// Bump this for every change to [`create`], and add the matching block in
/// [`crate::migrations::upgrade`]. Independent of the SQLite adapter's numbering: no PostgreSQL
/// database was ever upgraded from those versions.
pub const VERSION: i64 = 1;

/// The oldest version this build upgrades from.
pub const OLDEST_UPGRADABLE: i64 = 1;

/// The framework's row in `schema_version`.
pub const MODULE_NAME: &str = "saas";

/// Everything the framework crates persist. Pass it to `PgStore::migrate`, alone or beside the
/// consumer's own modules.
pub const FRAMEWORK: Module = Module { name: MODULE_NAME, version: VERSION, apply };

fn apply(conn: &mut PgConnection, from: i64) -> Fut<'_> {
	Box::pin(async move {
		if from == 0 {
			create(conn).await
		} else if from < OLDEST_UPGRADABLE {
			Err(Error::internal(format!(
				"database module '{MODULE_NAME}' is at version {from}, this build upgrades from \
				 {OLDEST_UPGRADABLE}"
			)))
		} else {
			crate::migrations::upgrade(conn, from).await
		}
	})
}

/// PostgreSQL resolves a `REFERENCES` when the table is created, so the constants run in
/// dependency order. The one true cycle (`accounts` → `refs` → `orgs` → `accounts`) is closed
/// by [`AUTH_CYCLE`] once all three exist.
async fn create(conn: &mut PgConnection) -> ClResult<()> {
	for ddl in [
		CORE, CURRENCIES, AUTH, REFS, AUTH_CYCLE, INVOICE, NAV, BILLING, OBJECTS, LLM, AGENT,
		SEARCH, DOCUMENTS, ENTITLE, PLANS,
	] {
		sqlx::raw_sql(ddl).execute(&mut *conn).await.db()?;
	}
	seed_root_org(conn).await
}

/// The root org: the one row with `kind = 'ROOT'`, and where operator authority lives.
async fn seed_root_org(conn: &mut PgConnection) -> ClResult<()> {
	// `WHERE NOT EXISTS`, not `ON CONFLICT DO NOTHING`: the latter would also swallow a uid
	// collision. The migration lock makes the pair atomic.
	sqlx::query(
		"INSERT INTO orgs (uid, kind, name, created_at)
		   SELECT $1, 'ROOT', 'Platform', $2
		    WHERE NOT EXISTS (SELECT 1 FROM orgs WHERE kind = 'ROOT')",
	)
	.bind(OrgId::generate().into_string())
	.bind(Timestamp::now().0)
	.execute(&mut *conn)
	.await
	.db()?;
	Ok(())
}

/// saas-core: the framework's own tables.
const CORE: &str = r"
CREATE TABLE vars (
	name		TEXT NOT NULL PRIMARY KEY,
	value		TEXT
);

CREATE TABLE settings (
	key		TEXT NOT NULL PRIMARY KEY,
	value		TEXT NOT NULL,			-- the registry owns the type
	updated_at	BIGINT NOT NULL,
	updated_by	BIGINT				-- accounts.id; no FK, survives anonymization
);

CREATE TABLE secrets (
	org_id		BIGINT NOT NULL DEFAULT 0,	-- orgs.id; 0 = global level; no FK (config-design.md §Scope)
	key		TEXT NOT NULL,
	nonce		BYTEA NOT NULL,			-- 12 bytes, fresh per write
	ciphertext	BYTEA NOT NULL,
	updated_at	BIGINT NOT NULL,
	updated_by	BIGINT,				-- accounts.id; no FK
	PRIMARY KEY (org_id, key)
);

-- No `max_attempts` column: the ceiling is the `jobs.max_attempts.<KIND>` settings family.
CREATE TABLE jobs (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	kind		TEXT NOT NULL,
	payload		TEXT NOT NULL DEFAULT '{}',	-- JSON
	dedup_key	TEXT UNIQUE,			-- NULL = no dedup; NULLs are distinct
	status		TEXT NOT NULL DEFAULT 'PENDING'
			CHECK (status IN ('PENDING','RUNNING','DONE','FAILED')),
	run_at		BIGINT NOT NULL,
	attempts	BIGINT NOT NULL DEFAULT 0,
	last_error	TEXT,				-- the human message
	created_at	BIGINT NOT NULL,
	done_at		BIGINT,
	err_code	TEXT,				-- `Error::parts()`; NULL when no `Error` stood behind it
	claimed_at	BIGINT,				-- `job_reclaim`'s age predicate
	result		TEXT				-- a handler's output, read back by dedup_key
);

-- `(run_at, id)` so the claim's `ORDER BY run_at, id` reads off the index.
CREATE INDEX idx_job_claim  ON jobs(run_at, id) WHERE status = 'PENDING';
CREATE INDEX idx_job_status ON jobs(status, created_at);

-- Hash, not the SQLite `(kind, payload)` B-tree: a B-tree entry is capped near 2.7 kB and a
-- payload is unbounded JSON. Every lookup by payload is an equality.
CREATE INDEX idx_job_kind_payload ON jobs USING hash (payload);

-- Append-only record of every mutation. No FK to accounts or orgs: the log outlives both.
CREATE TABLE audit_logs (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	at		BIGINT NOT NULL,
	account_id	BIGINT,
	org_id		BIGINT,
	ip		TEXT,
	entity		TEXT NOT NULL,			-- 'invoice', 'payment', 'secret', …
	entity_id	TEXT,				-- the uid, or the natural key
	action		TEXT NOT NULL,			-- 'ISSUE', 'STORNO', 'REFUND', 'AUDIT_EXPORT', …
	detail		TEXT,				-- JSON
	request_id	TEXT				-- ties to the structured log line
);

CREATE INDEX idx_audit_log_at      ON audit_logs(at DESC);
CREATE INDEX idx_audit_log_entity  ON audit_logs(entity, entity_id, at DESC);
CREATE INDEX idx_audit_log_account ON audit_logs(account_id, at DESC);
";

/// saas-invoice's currencies, ahead of the auth tables because `orgs.billing_currency`
/// references them.
const CURRENCIES: &str = r"
-- Enabled currencies and how a base-currency price converts into them.
CREATE TABLE currencies (
	code			TEXT NOT NULL PRIMARY KEY,	-- ISO-4217 alpha-3
	price_round_step	BIGINT NOT NULL DEFAULT 1,	-- minor units; HUF display step = 100
	cash_round_step		BIGINT CHECK (cash_round_step > 0),	-- minor units a cash payment rounds to; NULL = none
	mode			TEXT NOT NULL DEFAULT 'OFFICIAL'
				CHECK (mode IN ('FIXED','OFFICIAL')),
	fixed_rate_e6		BIGINT,				-- base units per 1 of this currency, when mode='FIXED'
	fee_bp			BIGINT NOT NULL DEFAULT 0,	-- conversion markup, basis points
	enabled			BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
	CHECK (mode <> 'FIXED' OR fixed_rate_e6 IS NOT NULL),
	CHECK (fixed_rate_e6 IS NULL OR fixed_rate_e6 > 0),
	CHECK (price_round_step > 0),
	-- A negative markup prices an item at 0.00; the 100x ceiling keeps the i128 product in range.
	CHECK (fee_bp >= 0 AND fee_bp <= 1000000)
);

-- The default base currency. HUF cash rounds to 5 Ft (2008. évi III. tv. 1-2. §).
INSERT INTO currencies (code, price_round_step, cash_round_step, mode, fixed_rate_e6)
	VALUES ('HUF', 100, 500, 'FIXED', 1000000)
	ON CONFLICT DO NOTHING;
";

/// saas-auth — accounts, orgs, memberships, api keys, TOTP, legal docs, consents.
const AUTH: &str = r#"
CREATE TABLE accounts (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid		TEXT NOT NULL UNIQUE,		-- 'acc_<ULID>'
	email		TEXT NOT NULL UNIQUE,		-- stored lowercased+trimmed; [GDPR]
	pwd_hash	TEXT,				-- argon2id; NULL = invited, no password yet
	name		TEXT,				-- [GDPR]
	locale		TEXT NOT NULL DEFAULT 'hu',
	status		TEXT NOT NULL DEFAULT 'PENDING'
			CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','ANONYMIZED')),
	token_epoch	BIGINT NOT NULL DEFAULT 0,	-- bump to invalidate this account's live JWTs
	failed_logins	BIGINT NOT NULL DEFAULT 0,
	locked_until	BIGINT,				-- lockout ladder
	activated_at	BIGINT,
	last_login_at	BIGINT,
	anonymized_at	BIGINT,
	created_at	BIGINT NOT NULL,
	pending_ref_id	BIGINT				-- refs.id, the FK added by AUTH_CYCLE
);

CREATE INDEX idx_account_status ON accounts(status);

-- The scope tree. Exactly one row has `kind = 'ROOT'`, and it is the only parentless row: an
-- operator is an account holding ADMIN or OWNER there. Identity never reuses an id, which the
-- FK-less agent_runs/llm_usage rows that outlive an org rely on.
CREATE TABLE orgs (
	id			BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid			TEXT NOT NULL UNIQUE,	-- 'org_<ULID>'
	parent_id		BIGINT REFERENCES orgs(id),	-- NULL only for the root
	kind			TEXT NOT NULL CHECK (kind IN ('ROOT','PERSONAL','SHARED')),
	name			TEXT NOT NULL,
	owner_account_id	BIGINT REFERENCES accounts(id),	-- NULL for the root
	billing_currency	TEXT REFERENCES currencies(code),	-- NULL = setting `currency.base`
	status			TEXT NOT NULL DEFAULT 'ACTIVE'
				CHECK (status IN ('ACTIVE','SUSPENDED')),
	created_at		BIGINT NOT NULL,
	slug			TEXT			-- optional public handle, case-insensitive; refs::validate_slug
);

-- integrity: a slug names one org, case-insensitively (SQLite: `COLLATE NOCASE`).
CREATE UNIQUE INDEX idx_org_slug ON orgs(lower(slug)) WHERE slug IS NOT NULL;

-- exactly one personal org per account; shared orgs are unconstrained
CREATE UNIQUE INDEX idx_org_personal
	ON orgs(owner_account_id) WHERE kind = 'PERSONAL';

-- integrity: this index is what makes the `kind = 'ROOT'` lookup single-row.
CREATE UNIQUE INDEX idx_org_root   ON orgs(kind) WHERE kind = 'ROOT';
CREATE INDEX        idx_org_parent ON orgs(parent_id);

CREATE TABLE memberships (
	org_id		BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
	account_id	BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
	role		TEXT NOT NULL CHECK (role IN ('OWNER','ADMIN','MEMBER')),
	accepted_at	BIGINT,				-- NULL only on legacy rows; `token::pick_org` skips them
	created_at	BIGINT NOT NULL,
	PRIMARY KEY (org_id, account_id)
);

CREATE INDEX idx_membership_account ON memberships(account_id);

CREATE TABLE api_keys (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid		TEXT NOT NULL UNIQUE,		-- 'key_<ULID>'
	org_id		BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
	account_id	BIGINT NOT NULL REFERENCES accounts(id),
	name		TEXT NOT NULL,
	prefix		TEXT NOT NULL UNIQUE,		-- first 8 chars of the key: the lookup handle
	key_hash	TEXT NOT NULL,			-- SHA-256 hex of server-made entropy, so no stretching
	scopes		TEXT NOT NULL DEFAULT '[]',	-- JSON array of route scopes
	last_used_at	BIGINT,
	expires_at	BIGINT,
	revoked_at	BIGINT,
	created_at	BIGINT NOT NULL
);

CREATE INDEX idx_api_key_org ON api_keys(org_id);

CREATE TABLE totp_credentials (
	account_id	BIGINT NOT NULL PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
	secret_nonce	BYTEA NOT NULL,
	secret_enc	BYTEA NOT NULL,			-- AES-256-GCM under HKDF(MASTER_KEY, 'totp')
	digits		BIGINT NOT NULL DEFAULT 6,
	period		BIGINT NOT NULL DEFAULT 30,
	recovery_hashes	TEXT NOT NULL DEFAULT '[]',	-- JSON array of argon2id hashes; consumed by removal
	last_used_step	BIGINT,				-- replay guard: the last accepted time step
	confirmed_at	BIGINT,				-- NULL = enrolment begun, not yet verified
	created_at	BIGINT NOT NULL
);

-- Account-scoped: a passkey is the person's. `credential` is the serialized `webauthn-rs`
-- `Passkey`, so the signature counter travels inside it.
CREATE TABLE webauthn_credentials (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_id	BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
	credential_id	TEXT NOT NULL UNIQUE,		-- base64url; the lookup handle
	credential	TEXT NOT NULL,
	name		TEXT NOT NULL,			-- "Chrome on macOS", user-editable
	created_at	BIGINT NOT NULL,
	last_used_at	BIGINT
);

CREATE INDEX idx_webauthn_account ON webauthn_credentials(account_id);

CREATE TABLE legal_docs (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	kind		TEXT NOT NULL
			CHECK (kind IN ('TOS','PRIVACY','EINVOICE','WITHDRAWAL_WAIVER')),
	locale		TEXT NOT NULL,			-- 'hu', 'en'
	version		TEXT NOT NULL,			-- '2026-09-01'
	title		TEXT NOT NULL,
	body		TEXT NOT NULL,			-- Markdown, verbatim as presented
	sha256		TEXT NOT NULL,			-- hex SHA-256 of `body`
	effective_from	BIGINT NOT NULL,
	created_at	BIGINT NOT NULL,
	UNIQUE (kind, locale, version)
);

CREATE TABLE consents (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_id	BIGINT NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
	org_id		BIGINT REFERENCES orgs(id),	-- NULL for account-level consent
	kind		TEXT NOT NULL
			CHECK (kind IN ('TOS','PRIVACY','EINVOICE','WITHDRAWAL_WAIVER')),
	legal_doc_id	BIGINT REFERENCES legal_docs(id),
	doc_version	TEXT NOT NULL,			-- copied, survives a legal_doc purge
	doc_sha256	TEXT NOT NULL,			-- copied, ditto
	granted		BIGINT NOT NULL DEFAULT 1 CHECK (granted IN (0,1)),
	at		BIGINT NOT NULL,
	ip		TEXT,				-- evidence; retained through anonymization
	user_agent	TEXT,
	withdrawn_at	BIGINT
);

CREATE INDEX idx_consent_account ON consents(account_id, kind, at DESC);
"#;

/// saas-core `refs` — redeemable codes and their attribution rows.
const REFS: &str = r"
CREATE TABLE refs (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid		TEXT NOT NULL UNIQUE,		-- 'ref_<ULID>'
	code		TEXT NOT NULL,			-- random or a chosen slug; unique case-insensitively
	type		TEXT NOT NULL,			-- open: 'signup', 'org_invite', an app's own
	org_id		BIGINT NOT NULL REFERENCES orgs(id),	-- the owner
	created_by	BIGINT,				-- accounts.id; no FK, outlives the account
	target		TEXT,
	email		TEXT,				-- lowercased; NULL = anyone
	params		TEXT NOT NULL DEFAULT '{}',	-- JSON object
	uses_left	BIGINT CHECK (uses_left >= 0),	-- NULL = unlimited
	expires_at	BIGINT,
	status		TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','REVOKED')),
	created_at	BIGINT NOT NULL
);

-- integrity (SQLite: `UNIQUE COLLATE NOCASE`)
CREATE UNIQUE INDEX idx_ref_code ON refs(lower(code));
CREATE INDEX idx_ref_org ON refs(org_id, type);

CREATE TABLE ref_uses (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ref_id		BIGINT NOT NULL REFERENCES refs(id),
	account_id	BIGINT NOT NULL,
	org_id		BIGINT NOT NULL,
	at		BIGINT NOT NULL,
	invoice_uid	TEXT,				-- the draft holding the use; no FK: deleted under it
	held		BIGINT NOT NULL DEFAULT 0,	-- 1 until paid; held with its invoice gone = unused
	UNIQUE (ref_id, account_id)			-- integrity: one use per account
);
";

/// Closes the `accounts` → `refs` → `orgs` → `accounts` cycle. `DEFERRABLE` (initially immediate)
/// so the migration runner's `SET CONSTRAINTS ALL DEFERRED` reaches it; at run time it checks per
/// statement, as SQLite does.
const AUTH_CYCLE: &str = r"
ALTER TABLE accounts ADD CONSTRAINT accounts_pending_ref_id_fkey
	FOREIGN KEY (pending_ref_id) REFERENCES refs(id) DEFERRABLE;
";

/// saas-invoice — rates, sellers and their versions, parties, services, the numbering series
/// and the invoice itself.
const INVOICE: &str = r"
-- Daily published rates, one row per (pair, date, source). 'EURHUF' is 1 EUR in HUF.
CREATE TABLE currency_rates (
	pair		TEXT NOT NULL,
	date		TEXT NOT NULL,			-- 'YYYY-MM-DD', the publication date
	source		TEXT NOT NULL CHECK (source IN ('MNB','ECB','BANK','MANUAL')),
	rate_e6		BIGINT NOT NULL CHECK (rate_e6 > 0),
	fetched_at	BIGINT NOT NULL,
	PRIMARY KEY (pair, date, source)
);

CREATE INDEX idx_currency_rate_lookup ON currency_rates(pair, source, date DESC);

-- VIES results, cached settings['vies.cache_days']. A stale row is a cache miss, not valid=0.
CREATE TABLE vies_checks (
	eu_vat_id	TEXT NOT NULL PRIMARY KEY,	-- country prefix + number, uppercased
	valid		BIGINT NOT NULL CHECK (valid IN (0,1)),
	name		TEXT,
	address		TEXT,
	request_id	TEXT,				-- VIES consultation number: the proof of the check
	checked_at	BIGINT NOT NULL
);

-- A seller company, owned by an org. Only the operational half; the statutory data is
-- versioned in `seller_versions`. No ON DELETE CASCADE: the row carries a taxpayer id and the
-- doc_series counter behind issued numbers, so deleting its org must fail loudly.
CREATE TABLE sellers (
	id			BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid			TEXT NOT NULL UNIQUE,		-- 'sel_<ULID>'
	org_id			BIGINT NOT NULL REFERENCES orgs(id),
	nav_base_url		TEXT NOT NULL,			-- outranks settings['nav.base_url'], then settings['deployment.env']
	nav_login		TEXT,				-- technical user login name
	series_code		TEXT NOT NULL DEFAULT 'A',	-- default series for new invoices
	closed_at		BIGINT,				-- read-only since; NULL = active
	payment_days		BIGINT CHECK (payment_days BETWEEN 0 AND 36500),	-- NULL = settings['invoice.default_payment_days']
	created_at		BIGINT NOT NULL
);

CREATE INDEX idx_seller_org ON sellers(org_id);

-- The seller's statutory data, versioned; `invoices.seller_ver` freezes the CURRENT one at
-- ISSUE. An edit rewrites the one DRAFT row; only `publish` archives CURRENT and promotes the
-- draft. A CURRENT or ARCHIVED row is never updated again — `saas-invoice`'s rule (arch-9).
-- `seller_ver`, not `id`, deliberately: `invoices` carries both `seller_id` and `seller_ver`.
CREATE TABLE seller_versions (
	seller_ver		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	seller_id		BIGINT NOT NULL REFERENCES sellers(id),
	status			TEXT NOT NULL DEFAULT 'DRAFT'
				CHECK (status IN ('DRAFT','CURRENT','ARCHIVED')),
	name			TEXT NOT NULL,
	country			TEXT NOT NULL DEFAULT 'HU',	-- ISO-3166-1 alpha-2
	tax_number		TEXT NOT NULL,			-- HU: 11 digits, punctuation stripped
	group_member_tax_no	TEXT,
	eu_vat_id		TEXT,				-- 'HU12345678'
	postcode		TEXT NOT NULL,
	city			TEXT NOT NULL,
	street			TEXT NOT NULL,
	bank_account		TEXT,				-- IBAN, or HU 16/24 digits
	bank_name		TEXT,
	small_business		BIGINT NOT NULL DEFAULT 0 CHECK (small_business IN (0,1)),
	vat_scheme		TEXT NOT NULL DEFAULT 'NORMAL'
				CHECK (vat_scheme IN ('NORMAL','ALANYI_MENTES')),
	-- The income-tax regime, separate from the VAT scheme: KATA + AAM is the common case.
	income_regime		TEXT NOT NULL DEFAULT 'NONE'
				CHECK (income_regime IN ('NONE','KATA','ATALANY')),
	-- Átalányadó költséghányad; NULL = the year's general rate (Szja tv. 53. §).
	expense_ratio_pct	BIGINT
				CHECK (expense_ratio_pct IS NULL OR expense_ratio_pct IN (40,45,50,80,90)),
	regime_since		TEXT,				-- 'YYYY-MM-DD', a mid-year start
	created_at		BIGINT NOT NULL,		-- when the draft was opened
	valid_from		BIGINT,				-- when it was published; NULL while DRAFT
	superseded_at		BIGINT,				-- when the next one was published
	CHECK ((status = 'DRAFT')    = (valid_from    IS NULL)),
	CHECK ((status = 'ARCHIVED') = (superseded_at IS NOT NULL))
);

-- Both integrity: at most one open draft and at most one live version per seller.
CREATE UNIQUE INDEX idx_seller_version_draft
	ON seller_versions(seller_id) WHERE status = 'DRAFT';

CREATE UNIQUE INDEX idx_seller_version_current
	ON seller_versions(seller_id) WHERE status = 'CURRENT';

CREATE INDEX idx_seller_version_history
	ON seller_versions(seller_id, valid_from DESC) WHERE status <> 'DRAFT';

-- The invoice recipient, owned by an org and never globally deduped. Editing a party never
-- rewrites an issued invoice, which froze its own copy at ISSUE.
CREATE TABLE billing_parties (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid		TEXT NOT NULL UNIQUE,		-- 'prt_<ULID>'
	org_id		BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
	kind		TEXT NOT NULL CHECK (kind IN ('P','C')),	-- private person | company
	name		TEXT NOT NULL,			-- [GDPR when kind='P']
	country		TEXT NOT NULL,			-- ISO-3166-1 alpha-2
	tax_number	TEXT,				-- HU: 11 digits (8 core + VAT code + county)
	eu_vat_id	TEXT,				-- country prefix + number, VIES-checkable
	group_tax_no	TEXT,
	postcode	TEXT,				-- [GDPR when kind='P']
	city		TEXT,				-- [GDPR when kind='P']
	street		TEXT,				-- [GDPR when kind='P']
	email		TEXT,				-- [GDPR when kind='P']
	is_default	BIGINT NOT NULL DEFAULT 0 CHECK (is_default IN (0,1)),
	payment_days	BIGINT CHECK (payment_days BETWEEN 0 AND 36500),	-- NULL = the seller's
	payment_method	TEXT CHECK (payment_method IN ('TRANSFER','CASH')),	-- NULL = TRANSFER
	created_at	BIGINT NOT NULL,
	updated_at	BIGINT NOT NULL
);

CREATE UNIQUE INDEX idx_billing_party_tax
	ON billing_parties(org_id, country, tax_number) WHERE tax_number IS NOT NULL;

CREATE UNIQUE INDEX idx_billing_party_default
	ON billing_parties(org_id) WHERE is_default = 1;

-- Serves `list_parties`' `ORDER BY is_default DESC, name` and `anonymize_account`'s org filter.
CREATE INDEX idx_billing_party_org
	ON billing_parties(org_id, is_default DESC, name);

-- Priced master data, in the base currency. `vat_code` is only the default.
CREATE TABLE services (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid		TEXT NOT NULL UNIQUE,		-- 'svc_<ULID>'
	org_id		BIGINT NOT NULL REFERENCES orgs(id),
	code		TEXT,				-- stable human handle, e.g. 'PLAN_PRO_M'
	name		TEXT NOT NULL,
	description	TEXT,
	unit		TEXT NOT NULL DEFAULT 'db',	-- NAV unitOfMeasure=OWN + unitOfMeasureOwn
	unit_price	BIGINT NOT NULL,		-- Money, base-currency minor units
	vat_code	TEXT NOT NULL
			CHECK (vat_code IN ('STD27','RED18','RED05','AAM','TAM','EUFAD37','HO','ATK')),
	active		BIGINT NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
	created_at	BIGINT NOT NULL,
	updated_at	BIGINT NOT NULL
);

-- `code` is unique per org, not globally.
CREATE UNIQUE INDEX idx_service_code   ON services(org_id, code);
CREATE INDEX        idx_service_active ON services(org_id, active, name);

-- The gapless counter, one row per (seller, kind, code, year). Allocation happens only inside
-- the issue transaction, so a rollback consumes no number.
CREATE TABLE doc_series (
	seller_id	BIGINT NOT NULL REFERENCES sellers(id),
	kind		TEXT NOT NULL,			-- 'INVOICE'; 'ORDER', 'QUOTE', … later
	code		TEXT NOT NULL,			-- 'A'
	year		BIGINT NOT NULL,		-- 2026
	next_no		BIGINT NOT NULL DEFAULT 1,
	format		TEXT NOT NULL DEFAULT '{code}{year}/{no:06}',
	PRIMARY KEY (seller_id, kind, code, year)
);

-- The central row: mutable as DRAFT, frozen from ISSUED on. PENDING is a DRAFT a gateway
-- payment has locked: unnumbered, never filed, immutable until the payment settles or dies.
-- Immutability after ISSUE is `saas-invoice`'s (every `UPDATE invoices` carries
-- `AND status = 'DRAFT'`), not a trigger's.
CREATE TABLE invoices (
	id			BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid			TEXT NOT NULL UNIQUE,		-- 'inv_<ULID>'
	request_id		TEXT,				-- consumer idempotency key, per org
	org_id			BIGINT NOT NULL REFERENCES orgs(id),
	seller_id		BIGINT NOT NULL REFERENCES sellers(id),
	seller_ver		BIGINT REFERENCES seller_versions(seller_ver),	-- frozen at ISSUE
	billing_party_id	BIGINT REFERENCES billing_parties(id) ON DELETE SET NULL,
	kind			TEXT NOT NULL DEFAULT 'NORMAL'
				CHECK (kind IN ('NORMAL','STORNO')),
	status			TEXT NOT NULL DEFAULT 'DRAFT'
				CHECK (status IN ('DRAFT','PENDING','ISSUED','PAID','STORNOED')),

	series_code		TEXT,				-- frozen at ISSUE
	series_year		BIGINT,				-- frozen at ISSUE
	number			TEXT,				-- rendered; NULL while DRAFT
	issued_at		BIGINT,
	fulfilment_date		TEXT,				-- 'YYYY-MM-DD'; Áfa tv. 55-58. §
	due_date		TEXT,				-- 'YYYY-MM-DD'
	period_start		TEXT,				-- 'YYYY-MM-DD'; settlement period, Áfa tv. 58. §
	period_end		TEXT,				-- 'YYYY-MM-DD'; both or neither
	payment_method		TEXT NOT NULL DEFAULT 'TRANSFER'
				CHECK (payment_method IN ('TRANSFER','CARD','CASH','OTHER')),

	original_invoice_id	BIGINT REFERENCES invoices(id),	-- STORNO -> the cancelled invoice
	modification_index	BIGINT,				-- always NULL in v1; MODIFY-ready

	currency		TEXT NOT NULL REFERENCES currencies(code),
	rate_e6			BIGINT NOT NULL DEFAULT 1000000,	-- base units per 1 of invoice currency, frozen
	rate_date		TEXT,				-- = fulfilment_date, or the last publication before it
	rate_source		TEXT CHECK (rate_source IN ('MNB','ECB','BANK','MANUAL')),
	huf_rate_e6		BIGINT,				-- invoice currency -> HUF; NULL iff currency='HUF'

	net			BIGINT NOT NULL DEFAULT 0,	-- = SUM(invoice_vat_groups.net)
	vat			BIGINT NOT NULL DEFAULT 0,	-- = SUM(invoice_vat_groups.vat)
	gross			BIGINT NOT NULL DEFAULT 0,	-- = net + vat
	paid_amount		BIGINT NOT NULL DEFAULT 0,	-- = SUM(payment_allocations.amount)
	paid_at			BIGINT,				-- set when paid_amount first reaches gross

	vat_note		TEXT,				-- mandatory legal text, from Verdict::note_key
	notes			TEXT,

	-- The invoice-level discount, kept because its apportioned share in the lines cannot be
	-- told apart from a line's own discount.
	discount_kind		TEXT CHECK (discount_kind IN ('AMOUNT','PERCENT')),
	discount_value		BIGINT,				-- AMOUNT: minor units; PERCENT: basis points

	-- ---- frozen buyer snapshot: written at ISSUE, never updated, never erased ----
	buyer_kind		TEXT CHECK (buyer_kind IN ('P','C')),
	buyer_name		TEXT,
	buyer_country		TEXT,
	buyer_tax_number	TEXT,
	buyer_eu_vat_id		TEXT,
	buyer_group_tax_no	TEXT,
	buyer_postcode		TEXT,
	buyer_city		TEXT,
	buyer_street		TEXT,
	-- The VIES verdict that justified reverse charge, as evidence `vies_checks` cannot keep.
	buyer_vies_request_id	TEXT,
	buyer_vies_checked_at	BIGINT,

	created_at		BIGINT NOT NULL,
	updated_at		BIGINT NOT NULL,
	version			BIGINT NOT NULL DEFAULT 0,	-- optimistic-concurrency token

	CHECK (status IN ('DRAFT','PENDING') OR number           IS NOT NULL),
	CHECK (status IN ('DRAFT','PENDING') OR issued_at        IS NOT NULL),
	CHECK (status IN ('DRAFT','PENDING') OR fulfilment_date  IS NOT NULL),
	CHECK (status IN ('DRAFT','PENDING') OR buyer_name       IS NOT NULL),
	CHECK (status IN ('DRAFT','PENDING') OR seller_ver       IS NOT NULL),
	CHECK (kind  <> 'STORNO' OR original_invoice_id IS NOT NULL),
	CHECK (currency <> 'HUF' OR huf_rate_e6 IS NULL),
	CHECK (status IN ('DRAFT','PENDING') OR currency = 'HUF' OR huf_rate_e6 IS NOT NULL),
	-- A zero rate freezes the statutory HUF figures (Áfa tv. 172. §) at 0.00.
	CHECK (rate_e6 > 0),
	CHECK (huf_rate_e6 IS NULL OR huf_rate_e6 > 0),
	-- Per org, not global; NULLs are distinct, so invoices with no `request_id` are unconstrained.
	UNIQUE (org_id, request_id),

	CHECK (paid_amount >= 0),
	CHECK (discount_kind IS NULL OR discount_value IS NOT NULL)
);

CREATE UNIQUE INDEX idx_invoice_number
	ON invoices(seller_id, number) WHERE number IS NOT NULL;

CREATE INDEX idx_invoice_org        ON invoices(org_id, id DESC);
CREATE INDEX idx_invoice_due        ON invoices(due_date) WHERE status = 'ISSUED';
CREATE INDEX idx_invoice_draft_age  ON invoices(updated_at) WHERE status IN ('DRAFT','PENDING');
CREATE INDEX idx_invoice_party      ON invoices(billing_party_id);
-- The audit export's index; its predicate is the export query's own `number IS NOT NULL`.
CREATE INDEX idx_invoice_issued
	ON invoices(seller_id, issued_at) WHERE number IS NOT NULL;

-- an invoice can be cancelled at most once
CREATE UNIQUE INDEX idx_invoice_storno_once
	ON invoices(original_invoice_id) WHERE kind = 'STORNO';

-- One row per billed item, frozen with its invoice. `vat` and `gross` are DISPLAY values
-- apportioned out of the group figure; summing them can differ from the group VAT and NAV
-- rejects that.
CREATE TABLE invoice_lines (
	id			BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	invoice_id		BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
	line_no			BIGINT NOT NULL,		-- 1-based; NAV lineNumber
	service_id		BIGINT REFERENCES services(id) ON DELETE SET NULL,
	description		TEXT NOT NULL,
	unit			TEXT NOT NULL,
	qty			BIGINT NOT NULL,		-- Qty, scaled 1e6
	unit_price		BIGINT NOT NULL,		-- Money, invoice-currency minor units
	discount_kind		TEXT CHECK (discount_kind IN ('AMOUNT','PERCENT')),
	discount_value		BIGINT,				-- AMOUNT: minor units; PERCENT: basis points
	discount_amount		BIGINT NOT NULL DEFAULT 0,	-- resolved; NAV lineDiscountValue
	discount_description	TEXT,
	net			BIGINT NOT NULL,		-- round_half_up(unit_price*qty/1e6) - discount_amount
	vat_code		TEXT NOT NULL
				CHECK (vat_code IN ('STD27','RED18','RED05','AAM','TAM','EUFAD37','HO','ATK')),
	vat_rate_bp		BIGINT NOT NULL,
	vat			BIGINT NOT NULL DEFAULT 0,	-- INFORMATIONAL ONLY
	gross			BIGINT NOT NULL DEFAULT 0,	-- net + vat, informational
	note			TEXT,				-- the caller's free text, apart from `description`
	UNIQUE (invoice_id, line_no),
	-- No `discount_amount >= 0`: a STORNO line negates every figure, discount included.
	CHECK (discount_kind IS NULL OR discount_value IS NOT NULL)
);

-- The authoritative per-rate-group figures. Grouped by vat_code, not by rate: AAM and TAM
-- are both 0 bp but are reported separately to NAV. `vat_huf` is mandatory on a foreign-currency
-- invoice (Áfa tv. 172. §); `saas-invoice` enforces it, a CHECK cannot reach the parent row.
CREATE TABLE invoice_vat_groups (
	invoice_id	BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
	vat_code	TEXT NOT NULL
			CHECK (vat_code IN ('STD27','RED18','RED05','AAM','TAM','EUFAD37','HO','ATK')),
	vat_rate_bp	BIGINT NOT NULL,
	net		BIGINT NOT NULL,		-- SUM of the group's line nets
	vat		BIGINT NOT NULL,		-- round_half_up(net * vat_rate_bp / 10000)
	gross		BIGINT NOT NULL,		-- net + vat
	net_huf		BIGINT,
	vat_huf		BIGINT,				-- MANDATORY when currency <> 'HUF'
	gross_huf	BIGINT,
	PRIMARY KEY (invoice_id, vat_code)
);

-- The rendered PDF as immutable evidence, content-addressed: the file lives at
-- {DATA_DIR}/documents/{sha[0..2]}/{sha[2..4]}/{sha}.pdf, so there is no `path` column.
CREATE TABLE invoice_documents (
	invoice_id		BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
	kind			TEXT NOT NULL DEFAULT 'PDF' CHECK (kind IN ('PDF')),
	sha256			TEXT NOT NULL,		-- hex SHA-256 of the file; also its location
	bytes			BIGINT NOT NULL,
	template_version	TEXT NOT NULL,		-- the Typst template that produced it
	rendered_at		BIGINT NOT NULL,
	PRIMARY KEY (invoice_id, kind)
);

CREATE INDEX idx_invoice_document_sha ON invoice_documents(sha256);
";

/// saas-nav: `nav_submissions`, one row per `(invoice_id, op)`, not one per attempt — retry lives
/// on the `jobs` row — and its archived exchange in `nav_submission_xml`, whose cascade keeps
/// `NavStore::release_batch` from orphaning it.
const NAV: &str = r"
CREATE TABLE nav_submissions (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	invoice_id	BIGINT NOT NULL REFERENCES invoices(id),
	op		TEXT NOT NULL CHECK (op IN ('CREATE','STORNO','ANNUL')),
	transaction_id	TEXT,				-- NAV transactionId
	idx		BIGINT,				-- 1-based index within the batch
	verdict		TEXT CHECK (verdict IN ('DONE','WARN','REJECTED','FAILED')),
	error_code	TEXT,
	error_msg	TEXT,
	created_at	BIGINT NOT NULL,
	done_at		BIGINT,
	batch_uid	TEXT,				-- the leader invoice's uid = the batch's NAV requestId
	-- An operator dealt with the filing. Never clears what NAV said, never makes it filable again.
	resolved_at	BIGINT
);

-- integrity: one filing record per (invoice_id, op)
CREATE UNIQUE INDEX idx_nav_submission_live ON nav_submissions(invoice_id, op);

CREATE INDEX idx_nav_submission_tx ON nav_submissions(transaction_id)
	WHERE transaction_id IS NOT NULL;

CREATE INDEX idx_nav_submission_batch ON nav_submissions(batch_uid)
	WHERE batch_uid IS NOT NULL;

CREATE TABLE nav_submission_xml (
	submission_id	BIGINT NOT NULL PRIMARY KEY
			REFERENCES nav_submissions(id) ON DELETE CASCADE,
	request_xml	TEXT,				-- archived for audit, `auth::redact`ed
	response_xml	TEXT				-- archived for audit, `auth::redact`ed
);
";

/// saas-billing: money received, and which invoice it settled. `kind` deliberately carries no
/// `CHECK`: the framework does not enumerate settlement sources.
const BILLING: &str = r"
CREATE TABLE payments (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid		TEXT NOT NULL UNIQUE,		-- 'pay_<ULID>'
	org_id		BIGINT NOT NULL REFERENCES orgs(id),
	kind		TEXT NOT NULL,			-- OPEN: 'BARION'|'TRANSFER'|'MANUAL'|'CREDIT'|…
	provider	TEXT,				-- PaymentProvider::id() when gateway-backed
	provider_ref	TEXT,				-- the gateway's payment id
	redirect_url	TEXT,				-- where to send the browser; kept so a retry can resume
	expires_at	BIGINT,				-- when the gateway must have given up; NULL for a manual entry
	request_id	TEXT,				-- our idempotency key, unique per org
	status		TEXT NOT NULL DEFAULT 'PENDING'
			CHECK (status IN ('PENDING','AWAITING_USER','RESERVED','AUTHORIZED',
			                  'SUCCEEDED','PARTIALLY_SUCCEEDED','FAILED','CANCELED',
			                  'EXPIRED','REFUNDED')),
	amount		BIGINT NOT NULL,		-- Money, minor units of `currencies`
	currency	TEXT NOT NULL REFERENCES currencies(code),
	refunded_amount	BIGINT NOT NULL DEFAULT 0,
	received_at	BIGINT,
	ext_ref		TEXT,				-- bank reference / remittance note, for matching
	note		TEXT,
	created_by	BIGINT,				-- accounts.id for MANUAL entries; no FK
	created_at	BIGINT NOT NULL,
	updated_at	BIGINT NOT NULL,
	CHECK (refunded_amount >= 0 AND refunded_amount <= amount)
);

CREATE INDEX idx_payment_org    ON payments(org_id, id DESC);
-- Per org, not global; NULLs stay distinct.
CREATE UNIQUE INDEX idx_payment_request_id ON payments(org_id, request_id);
CREATE INDEX idx_payment_ext    ON payments(ext_ref) WHERE ext_ref IS NOT NULL;
-- integrity: a replayed callback finds the one row, which the guarded transitions settle once.
CREATE UNIQUE INDEX idx_payment_provider_ref
	ON payments(provider, provider_ref) WHERE provider_ref IS NOT NULL;

-- `invoices.paid_amount` caches `SUM(amount)` over this, written in the same transaction.
CREATE TABLE payment_allocations (
	payment_id	BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
	invoice_id	BIGINT NOT NULL REFERENCES invoices(id),
	amount		BIGINT NOT NULL,		-- invoice-currency minor units; negative reverses
	allocated_at	BIGINT NOT NULL,
	allocated_by	BIGINT,				-- accounts.id for manual allocation; no FK
	PRIMARY KEY (payment_id, invoice_id)
);

CREATE INDEX idx_payment_allocation_invoice ON payment_allocations(invoice_id);
";

/// The generic object store: one JSON body per `(org_id, type, uid)` — the unique is what makes
/// a write an upsert — and the index rows a declared path extracts from it.
const OBJECTS: &str = r"
CREATE TABLE objects (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	org_id		BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
	type		TEXT NOT NULL,
	uid		TEXT NOT NULL,
	body		TEXT NOT NULL DEFAULT '{}',	-- JSON; parsed on read, never queried as a document
	created_at	BIGINT NOT NULL,
	updated_at	BIGINT NOT NULL,
	UNIQUE (org_id, type, uid)
);

CREATE INDEX idx_object_page ON objects(org_id, type, id DESC);

-- `value` is NULL when the body has no such path, which is also the row a query never matches.
CREATE TABLE object_index (
	object_id	BIGINT NOT NULL REFERENCES objects(id) ON DELETE CASCADE,
	path		TEXT NOT NULL,		-- a declared JSON path, e.g. '$.projectUid'
	value		TEXT,
	PRIMARY KEY (object_id, path)
);

-- ponytail: B-tree entries cap near 2.7 kB, so an indexed value longer than that fails the
-- write; switch to an expression index on a hash of `value` if real data hits it.
CREATE INDEX idx_object_index_lookup ON object_index (path, value, object_id);
";

/// `saas-llm`'s cost ledger and budgets. Created in every build, `ai` or not.
const LLM: &str = r"
CREATE TABLE llm_usage (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	at		BIGINT NOT NULL,
	run_uid		TEXT,
	account_id	BIGINT,				-- no FK: the ledger outlives the account
	org_id		BIGINT,				-- no FK: same reason
	subject		TEXT,				-- opaque budget key, e.g. 'project:prj_…'
	step		TEXT NOT NULL,
	kind		TEXT NOT NULL CHECK (kind IN ('llm','search','fetch')),
	provider	TEXT NOT NULL,
	model		TEXT NOT NULL,
	tokens_in	BIGINT NOT NULL,
	tokens_out	BIGINT NOT NULL,
	cost_micro_eur	BIGINT NOT NULL,
	retry		BIGINT NOT NULL CHECK (retry IN (0,1))
);

CREATE INDEX idx_llm_usage_at      ON llm_usage(at, cost_micro_eur);
CREATE INDEX idx_llm_usage_subject ON llm_usage(subject, cost_micro_eur) WHERE subject IS NOT NULL;

CREATE TABLE llm_budgets (
	subject			TEXT NOT NULL PRIMARY KEY,
	budget_micro_eur	BIGINT NOT NULL CHECK (budget_micro_eur >= 0),
	updated_at		BIGINT NOT NULL
);
";

/// `saas-agent`'s runs and the events each streamed; threads live in the app DB.
const AGENT: &str = r"
CREATE TABLE agent_runs (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid		TEXT NOT NULL UNIQUE,
	thread_uid	TEXT NOT NULL,			-- agent_threads.uid, in the app DB
	org_id		BIGINT NOT NULL,		-- no FK: the run record outlives the org
	account_id	BIGINT,				-- no FK; NULL once the account is erased
	role		TEXT NOT NULL,
	spec		TEXT NOT NULL,			-- JSON
	status		TEXT NOT NULL CHECK (status IN
			('queued','running','done','error','cancelled','interrupted')),
	error		TEXT,
	created_at	BIGINT NOT NULL,
	started_at	BIGINT,
	finished_at	BIGINT,
	heartbeat_at	BIGINT				-- the owning pool's lease; the stale sweep reads it
);

-- D2, one live run per thread: integrity, not performance.
CREATE UNIQUE INDEX idx_agent_runs_live ON agent_runs(thread_uid) WHERE status IN ('queued','running');
CREATE INDEX idx_agent_runs_account ON agent_runs(account_id) WHERE account_id IS NOT NULL;

CREATE TABLE agent_run_events (
	run_id		BIGINT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
	seq		BIGINT NOT NULL,
	kind		TEXT NOT NULL CHECK (kind IN
			('queued','delta','tool_call','tool_result','message','done','error')),
	payload		TEXT NOT NULL,
	at		BIGINT NOT NULL,
	PRIMARY KEY (run_id, seq)
);
";

/// `saas-search`'s fetched pages, shared across orgs, and its search-result cache.
const SEARCH: &str = r"
CREATE TABLE sources (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid		TEXT NOT NULL UNIQUE,
	url		TEXT NOT NULL,
	title		TEXT NOT NULL,
	fetched_at	BIGINT NOT NULL,
	sha256		TEXT NOT NULL,			-- hex, of text
	text		TEXT NOT NULL
);

CREATE INDEX idx_sources_url ON sources(url, fetched_at);

CREATE TABLE search_cache (
	provider	TEXT NOT NULL,
	query		TEXT NOT NULL,
	lang		TEXT NOT NULL,			-- '' when absent, so it takes part in the key
	market		TEXT NOT NULL,			-- same
	results		TEXT NOT NULL,			-- JSON
	fetched_at	BIGINT NOT NULL,
	PRIMARY KEY (provider, query, lang, market)
);
";

/// `saas-pdf`'s app documents. Erasable with their org, unlike `invoice_documents`; both share
/// the `documents/` file tree, so a file may go only when neither names it.
const DOCUMENTS: &str = r"
CREATE TABLE documents (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid		TEXT NOT NULL UNIQUE,			-- 'doc_<ULID>'
	org_id		BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
	template	TEXT NOT NULL,
	job_key		TEXT NOT NULL,			-- the RENDER_DOC dedup_key
	sha256		TEXT,				-- NULL until rendered; also its location
	bytes		BIGINT,
	created_at	BIGINT NOT NULL
);

CREATE INDEX idx_documents_sha ON documents(sha256);
";

/// `saas-entitle`'s grants and the usage ledger drawn from them.
const ENTITLE: &str = r"
CREATE TABLE grants (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid		TEXT NOT NULL UNIQUE,			-- 'grt_<ULID>'
	org_id		BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
	key		TEXT NOT NULL,
	amount		BIGINT NOT NULL CHECK (amount >= 0),
	valid_from	BIGINT NOT NULL,
	valid_until	BIGINT,					-- NULL = forever
	source		TEXT NOT NULL
			CHECK (source IN ('SUBSCRIPTION', 'PURCHASE', 'REWARD', 'MANUAL', 'TRIAL')),
	source_ref	TEXT,					-- NULL is never deduplicated
	created_at	BIGINT NOT NULL,
	UNIQUE (org_id, key, source, source_ref)
);

CREATE INDEX idx_grants_active ON grants(org_id, key, valid_until);

-- One row per grant a debit drew from, numbered by `seq`; the unique makes a retried
-- (org, idem_key) debit once.
CREATE TABLE usage (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	org_id		BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
	key		TEXT NOT NULL,
	grant_id	BIGINT REFERENCES grants(id) ON DELETE CASCADE,
	amount		BIGINT NOT NULL,
	at		BIGINT NOT NULL,
	idem_key	TEXT NOT NULL,
	seq		BIGINT NOT NULL,
	account_id	BIGINT,					-- no FK: the ledger outlives the account
	UNIQUE (org_id, idem_key, seq)
);

CREATE INDEX idx_usage_grant ON usage(grant_id);
";

/// `saas-plans`' offer catalogue, subscriptions and the invoices they caused. `"interval"` is
/// quoted: `INTERVAL` is a type keyword, and every query naming the column quotes it too.
const PLANS: &str = r#"
CREATE TABLE offers (
	id		BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid		TEXT NOT NULL UNIQUE,			-- 'ofr_<ULID>'
	seller_org_id	BIGINT NOT NULL REFERENCES orgs(id),
	code		TEXT NOT NULL,
	name		TEXT NOT NULL,
	kind		TEXT NOT NULL CHECK (kind IN ('ONE_TIME', 'RECURRING')),
	service_id	BIGINT NOT NULL REFERENCES services(id),
	family		TEXT,					-- tiers: one live sub per (org, family)
	rank		BIGINT NOT NULL DEFAULT 0,
	"interval"	TEXT CHECK ("interval" IN ('MONTH', 'YEAR')),
	interval_count	BIGINT CHECK (interval_count > 0),
	validity_days	BIGINT CHECK (validity_days > 0),	-- ONE_TIME; NULL = forever
	trial_days	BIGINT NOT NULL DEFAULT 0 CHECK (trial_days >= 0),
	active		BIGINT NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
	created_at	BIGINT NOT NULL,
	updated_at	BIGINT NOT NULL,
	UNIQUE (seller_org_id, code),
	CHECK ((kind = 'RECURRING') = ("interval" IS NOT NULL AND interval_count IS NOT NULL))
);

CREATE TABLE offer_prices (
	offer_id	BIGINT NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
	currency	TEXT NOT NULL REFERENCES currencies(code),
	amount		BIGINT NOT NULL CHECK (amount >= 0),	-- minor units
	PRIMARY KEY (offer_id, currency)
);

CREATE TABLE offer_entitlements (
	offer_id	BIGINT NOT NULL REFERENCES offers(id) ON DELETE CASCADE,
	key		TEXT NOT NULL,
	amount		BIGINT NOT NULL CHECK (amount >= 0),
	per_seat	BIGINT NOT NULL DEFAULT 0 CHECK (per_seat IN (0, 1)),
	PRIMARY KEY (offer_id, key)
);

CREATE TABLE subscriptions (
	id			BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uid			TEXT NOT NULL UNIQUE,		-- 'sub_<ULID>'
	org_id			BIGINT NOT NULL REFERENCES orgs(id),
	offer_id		BIGINT NOT NULL REFERENCES offers(id),
	family			TEXT,
	qty			BIGINT NOT NULL DEFAULT 1 CHECK (qty > 0),
	status			TEXT NOT NULL
				CHECK (status IN ('TRIALING', 'ACTIVE', 'PAST_DUE', 'SUSPENDED', 'CANCELED')),
	currency		TEXT NOT NULL REFERENCES currencies(code),
	price			BIGINT NOT NULL CHECK (price >= 0),	-- per seat per period, grandfathered
	period_start		BIGINT NOT NULL,
	period_end		BIGINT NOT NULL,
	cancel_at_period_end	BIGINT NOT NULL DEFAULT 0 CHECK (cancel_at_period_end IN (0, 1)),
	next_offer_id		BIGINT REFERENCES offers(id),
	next_qty		BIGINT CHECK (next_qty > 0),
	pay_method		TEXT NOT NULL CHECK (pay_method IN ('CARD', 'TRANSFER')),
	provider		TEXT,
	recurrence_ref		TEXT,				-- gateway reference, not a credential
	coupon_ref_id		BIGINT REFERENCES refs(id),
	coupon_periods_left	BIGINT,
	created_at		BIGINT NOT NULL,
	updated_at		BIGINT NOT NULL,
	billing_anchor		BIGINT NOT NULL DEFAULT 0	-- first paid period start; renewals step from it
);

-- Integrity, not a lookup aid: one live subscription per (org, family).
CREATE UNIQUE INDEX idx_sub_family_live ON subscriptions(org_id, family)
	WHERE family IS NOT NULL AND status <> 'CANCELED';
CREATE INDEX idx_sub_org ON subscriptions(org_id);
CREATE INDEX idx_sub_due ON subscriptions(period_end)
	WHERE status IN ('TRIALING', 'ACTIVE', 'PAST_DUE');

-- Why an invoice exists. CASCADE: a deleted or swept draft takes its link with it.
CREATE TABLE plan_invoices (
	invoice_id	BIGINT NOT NULL PRIMARY KEY REFERENCES invoices(id) ON DELETE CASCADE,
	subscription_id	BIGINT REFERENCES subscriptions(id),
	offer_id	BIGINT NOT NULL REFERENCES offers(id),
	kind		TEXT NOT NULL CHECK (kind IN ('PURCHASE', 'SUBSCRIBE', 'RENEWAL', 'UPGRADE')),
	qty		BIGINT NOT NULL CHECK (qty > 0),
	period_start	BIGINT,
	period_end	BIGINT,
	coupon_ref_id	BIGINT REFERENCES refs(id),
	prev_offer_id	BIGINT REFERENCES offers(id),	-- UPGRADE: the tier it replaced
	prev_qty	BIGINT,
	CHECK ((kind = 'PURCHASE') = (subscription_id IS NULL))
);

CREATE INDEX idx_plan_invoices_sub ON plan_invoices(subscription_id, period_start);
"#;

// vim: ts=4
